/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.employee;

import entity.ThucUong;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import utils.ErrorPopup;
import utils.IconManager;

/**
 *
 * @author mac
 */
public  class OrderManagerView extends javax.swing.JPanel {

     
     
    IconManager im = new IconManager();
    private  String numberTable;
    private  CardLayout cardLayout = new CardLayout();
    IntroduceOrderView introduceOrder = new IntroduceOrderView();
    JPanel panel = new JPanel();
    public OrderManagerView() {
        initComponents();
        
        
        
        orderDetailPanel.setLayout(cardLayout);
        orderDetailPanel.add(introduceOrder, "intro");
        
        
//        JScrollPane scrollPane = new JScrollPane(panel);
//        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
//        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
//        scrollPane.setBounds(50, 30, 300, 50);
//        
//        setLayout(cardLayout);
//        add(scrollPane, BorderLayout.CENTER);

    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }
    
   
    

    
    public JPanel getTableManPnl() {
        return tableManPnl;
    }


    
    
    public void showError(String message) {
        ErrorPopup.show(new Exception(message));
    }

    public void showError(Exception e) {
        ErrorPopup.show(e);
    }

    public JPanel getOrderDetailPanel() {
        return orderDetailPanel;
    }
    

    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tableScrollPanel = new javax.swing.JScrollPane();
        tableManPnl = new javax.swing.JPanel();
        orderDetailPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1008, 680));
        setPreferredSize(new java.awt.Dimension(1008, 680));
        setLayout(new java.awt.BorderLayout());

        tableScrollPanel.setToolTipText("");
        tableScrollPanel.setVerifyInputWhenFocusTarget(false);

        tableManPnl.setMaximumSize(new java.awt.Dimension(200, 3800));
        tableManPnl.setPreferredSize(new java.awt.Dimension(480, 200));
        tableManPnl.setRequestFocusEnabled(false);
        tableManPnl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15));
        tableScrollPanel.setViewportView(tableManPnl);

        add(tableScrollPanel, java.awt.BorderLayout.CENTER);
        tableScrollPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout orderDetailPanelLayout = new javax.swing.GroupLayout(orderDetailPanel);
        orderDetailPanel.setLayout(orderDetailPanelLayout);
        orderDetailPanelLayout.setHorizontalGroup(
            orderDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        orderDetailPanelLayout.setVerticalGroup(
            orderDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        add(orderDetailPanel, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel orderDetailPanel;
    private javax.swing.JPanel tableManPnl;
    private javax.swing.JScrollPane tableScrollPanel;
    // End of variables declaration//GEN-END:variables
}
