/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.employee;

import javax.swing.JButton;
import utils.IconManager;

/**
 *
 * @author mac
 */
public class TableItem extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    IconManager icon = new IconManager();
    public TableItem(String numberTalbeText) {
        initComponents();
        numberTable.setIcon(icon.getIcon("circle-table (1).png"));
        numberTable.setText(numberTalbeText);
    }

    public JButton getNumberTable() {
        return numberTable;
    }

    public void setNumberTable(JButton numberTable) {
        this.numberTable = numberTable;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberTable = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        numberTable.setBackground(java.awt.Color.orange);
        numberTable.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numberTable.setForeground(new java.awt.Color(255, 255, 255));
        numberTable.setText("Bàn");
        numberTable.setToolTipText("");
        numberTable.setBorderPainted(false);
        numberTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        numberTable.setIconTextGap(0);
        numberTable.setIgnoreRepaint(true);
        numberTable.setPreferredSize(new java.awt.Dimension(100, 100));
        numberTable.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        numberTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTableActionPerformed(evt);
            }
        });
        add(numberTable, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void numberTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton numberTable;
    // End of variables declaration//GEN-END:variables
}
